# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AI_test3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from MatplotlibWidget import MatplotlibWidget

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(641, 1000)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 631, 991))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.consoleEdit = QtWidgets.QTextEdit(self.tab)
        self.consoleEdit.setGeometry(QtCore.QRect(0, 380, 611, 101))
        self.consoleEdit.setObjectName("consoleEdit")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 330, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.btn_test_dir = QtWidgets.QPushButton(self.tab)
        self.btn_test_dir.setGeometry(QtCore.QRect(10, 170, 101, 28))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.btn_test_dir.setFont(font)
        self.btn_test_dir.setObjectName("btn_test_dir")
        self.heightEdit = QtWidgets.QLineEdit(self.tab)
        self.heightEdit.setGeometry(QtCore.QRect(150, 90, 51, 31))
        self.heightEdit.setObjectName("heightEdit")
        self.train_dir_display = QtWidgets.QTextEdit(self.tab)
        self.train_dir_display.setGeometry(QtCore.QRect(150, 50, 461, 31))
        self.train_dir_display.setObjectName("train_dir_display")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 131, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(220, 90, 131, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.widthEdit = QtWidgets.QLineEdit(self.tab)
        self.widthEdit.setGeometry(QtCore.QRect(280, 90, 51, 31))
        self.widthEdit.setObjectName("widthEdit")
        self.btn_train_dir = QtWidgets.QPushButton(self.tab)
        self.btn_train_dir.setGeometry(QtCore.QRect(10, 50, 101, 28))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.btn_train_dir.setFont(font)
        self.btn_train_dir.setObjectName("btn_train_dir")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(10, 15, 441, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.test_dir_display_2 = QtWidgets.QTextEdit(self.tab)
        self.test_dir_display_2.setGeometry(QtCore.QRect(150, 170, 461, 31))
        self.test_dir_display_2.setObjectName("test_dir_display_2")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(10, 210, 771, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(10, 230, 201, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(10, 260, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.epochEdit = QtWidgets.QLineEdit(self.tab)
        self.epochEdit.setGeometry(QtCore.QRect(80, 260, 51, 31))
        self.epochEdit.setObjectName("epochEdit")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(150, 260, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.batchEdit = QtWidgets.QLineEdit(self.tab)
        self.batchEdit.setGeometry(QtCore.QRect(250, 260, 51, 31))
        self.batchEdit.setObjectName("batchEdit")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(320, 260, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gpuratioEdit = QtWidgets.QLineEdit(self.tab)
        self.gpuratioEdit.setGeometry(QtCore.QRect(420, 260, 51, 31))
        self.gpuratioEdit.setObjectName("gpuratioEdit")
        self.chkB_finetune = QtWidgets.QCheckBox(self.tab)
        self.chkB_finetune.setGeometry(QtCore.QRect(10, 300, 85, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.chkB_finetune.setFont(font)
        self.chkB_finetune.setObjectName("chkB_finetune")
        self.chkB_save_ckpt = QtWidgets.QCheckBox(self.tab)
        self.chkB_save_ckpt.setGeometry(QtCore.QRect(130, 300, 121, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.chkB_save_ckpt.setFont(font)
        self.chkB_save_ckpt.setChecked(True)
        self.chkB_save_ckpt.setObjectName("chkB_save_ckpt")
        self.btn_data_process = QtWidgets.QPushButton(self.tab)
        self.btn_data_process.setGeometry(QtCore.QRect(250, 310, 141, 61))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.btn_data_process.setFont(font)
        self.btn_data_process.setObjectName("btn_data_process")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(10, 120, 771, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(10, 140, 431, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 441, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.btn_exam_dir = QtWidgets.QPushButton(self.tab_2)
        self.btn_exam_dir.setGeometry(QtCore.QRect(10, 60, 101, 28))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.btn_exam_dir.setFont(font)
        self.btn_exam_dir.setObjectName("btn_exam_dir")
        self.exam_dir_display = QtWidgets.QTextEdit(self.tab_2)
        self.exam_dir_display.setGeometry(QtCore.QRect(150, 60, 461, 31))
        self.exam_dir_display.setPlaceholderText("")
        self.exam_dir_display.setObjectName("exam_dir_display")
        self.graphV_normal = QtWidgets.QGraphicsView(self.tab_2)
        self.graphV_normal.setGeometry(QtCore.QRect(10, 140, 601, 401))
        self.graphV_normal.setObjectName("graphV_normal")
        self.btn_prev = QtWidgets.QPushButton(self.tab_2)
        self.btn_prev.setGeometry(QtCore.QRect(10, 550, 93, 28))
        self.btn_prev.setObjectName("btn_prev")
        self.btn_next = QtWidgets.QPushButton(self.tab_2)
        self.btn_next.setGeometry(QtCore.QRect(100, 550, 93, 28))
        self.btn_next.setObjectName("btn_next")
        self.btn_detect = QtWidgets.QPushButton(self.tab_2)
        self.btn_detect.setGeometry(QtCore.QRect(190, 550, 93, 28))
        self.btn_detect.setObjectName("btn_detect")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(10, 590, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(10, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.textEdit_exam = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_exam.setGeometry(QtCore.QRect(10, 620, 601, 111))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.textEdit_exam.setFont(font)
        self.textEdit_exam.setObjectName("textEdit_exam")
        self.label_exam_warn = QtWidgets.QLabel(self.tab_2)
        self.label_exam_warn.setGeometry(QtCore.QRect(330, 560, 281, 16))
        self.label_exam_warn.setText("")
        self.label_exam_warn.setObjectName("label_exam_warn")
        self.tabWidget.addTab(self.tab_2, "")

        # add by Johnny
        self.matplotlibwidget_dynamic = MatplotlibWidget(self.tab)
        self.matplotlibwidget_dynamic.setEnabled(True)
        self.matplotlibwidget_dynamic.setHidden(True)
        self.matplotlibwidget_dynamic.setGeometry(QtCore.QRect(0, 500, 620, 450))
        self.matplotlibwidget_dynamic.setObjectName("matplotlibwidget_dynamic")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "訊息顯示窗口"))
        self.btn_test_dir.setText(_translate("Form", "資料夾選擇"))
        self.heightEdit.setText(_translate("Form", "64"))
        self.train_dir_display.setPlaceholderText(_translate("Form", "./goodsamples"))
        self.label_3.setText(_translate("Form", "尺寸調整:高度"))
        self.label_4.setText(_translate("Form", "寬度"))
        self.widthEdit.setText(_translate("Form", "64"))
        self.btn_train_dir.setText(_translate("Form", "資料夾選擇"))
        self.label_11.setText(_translate("Form", "正樣本訓練資料選擇(供AI模型訓練用)"))
        self.test_dir_display_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.test_dir_display_2.setPlaceholderText(_translate("Form", "./xxx"))
        self.label_13.setText(_translate("Form", "AI模型參數設定"))
        self.label_14.setText(_translate("Form", "epoch:"))
        self.epochEdit.setText(_translate("Form", "10"))
        self.label_15.setText(_translate("Form", "batch size:"))
        self.batchEdit.setText(_translate("Form", "1"))
        self.label_16.setText(_translate("Form", "GPU ratio:"))
        self.gpuratioEdit.setText(_translate("Form", "0.3"))
        self.chkB_finetune.setText(_translate("Form", "fine tune"))
        self.chkB_save_ckpt.setText(_translate("Form", "save ckpt"))
        self.btn_data_process.setText(_translate("Form", "開始訓練"))
        self.label_12.setText(_translate("Form", "驗證資料選擇(供AI模型訓練後驗證準確率)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "訓練"))
        self.label_17.setText(_translate("Form", "檢測圖片來源"))
        self.btn_exam_dir.setText(_translate("Form", "資料夾選擇"))
        self.btn_prev.setText(_translate("Form", "上一張"))
        self.btn_next.setText(_translate("Form", "下一張"))
        self.btn_detect.setText(_translate("Form", "檢測"))
        self.label_2.setText(_translate("Form", "檢測結果"))
        self.label_9.setText(_translate("Form", "原始圖顯示"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "檢測"))

